In [1]:
import numpy as np
import pandas as pd
import re
import string

In [2]:
data=pd.read_csv("Documents/rt_reviews.csv",encoding="cp1252")

In [3]:
data.head()

Freshness                                             Review
0     fresh   Manakamana doesn't answer any questions, yet ...
1     fresh   Wilfully offensive and powered by a chest-thu...
2    rotten   It would be difficult to imagine material mor...
3    rotten   Despite the gusto its star brings to the role...
4    rotten   If there was a good idea at the core of this ...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 480000 entries, 0 to 479999
Data columns (total 2 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   Freshness  480000 non-null  object
 1   Review     480000 non-null  object
dtypes: object(2)
memory usage: 7.3+ MB


In [5]:
data["Freshness"].value_counts()

fresh     240000
rotten    240000
Name: Freshness, dtype: int64

In [6]:
data.isnull().sum()

Freshness    0
Review       0
dtype: int64

In [7]:
a=[]
stop_words = ["a", "an", "the", "and", "or", "but", "is", "am", "are", "was", "were", "be", "being", "been", "have", "has", "had", "do", "does", "did", "will", "would", "shall", "should", "can", "could", "may", "might", "must"]
for i in data["Review"]:
        msg1=" "
        message = i.lower()
        message = message.split()
        words=[]
        for word in message:
            word=re.sub("[^a-zA-Z0-9/s]","",word)
            if word not in stop_words:
              words.append(word)

        msg1=" ".join(words)
        a.append(msg1)

In [8]:
data["Review"]=a

In [9]:
data["Review"] = data["Review"].apply(lambda x: x.translate(str.maketrans("", "", string.punctuation)))

In [10]:
#we need to divide data into three catogoeries
size = data.shape[0]

train_size = int(size*0.6)
dev_size = int(size*0.2)
train_data = data.iloc[:train_size,:]
dev_data   = data.iloc[train_size:train_size+dev_size+1,:]
test_data  = data.iloc[train_size+dev_size:,:]

In [11]:
train_data.head()

Freshness                                             Review
0     fresh  manakamana doesnt answer any questions yet mak...
1     fresh  wilfully offensive powered by chestthumping ma...
2    rotten  it difficult to imagine material more wrong fo...
3    rotten  despite gusto its star brings to role its hard...
4    rotten  if there good idea at core of this film its bu...

In [12]:
dev_data.head()

Freshness                                             Review
288000    rotten  tepid attempt at making alien abduction yarn i...
288001     fresh  perfectly serviceable raceagainsttheclock thri...
288002     fresh                    poetic pulp movie made with joy
288003     fresh  thirst just best horror movie of year so far p...
288004     fresh  expect same easy chemistry between two main le...

In [13]:
test_data.head()

Freshness                                             Review
384000    rotten  film that abuses its ridiculous premise never ...
384001     fresh  for any age its amiable harmlessly entertainin...
384002     fresh  its incredibly stirring documentary one which ...
384003     fresh  lennons spirit like his music shines through t...
384004    rotten  try as it to build sense of mystery out of sto...

In [14]:
# def count_of_word(data):
count_of_word={}
for i in train_data["Review"]:
    for word in i.split():
        if word in count_of_word:
            count_of_word[word]+=1
        else:
            count_of_word[word]=1
words=[i for i,j in count_of_word.items() if j>=5]
words[:10]

['doesnt',
 'answer',
 'any',
 'questions',
 'yet',
 'makes',
 'its',
 'point',
 'like',
 'rest']

In [15]:
#index to word conversion
t=0
word_to_index={}
index_to_word={}
for i in words:
    word_to_index[t]=i
    index_to_word[i]=t
    t+=1

In [16]:
word_to_index

{0: 'doesnt',
 1: 'answer',
 2: 'any',
 3: 'questions',
 4: 'yet',
 5: 'makes',
 6: 'its',
 7: 'point',
 8: 'like',
 9: 'rest',
 10: 'of',
 11: 'our',
 12: 'planet',
 13: 'picturesque',
 14: 'far',
 15: 'from',
 16: 'kingdom',
 17: 'wilfully',
 18: 'offensive',
 19: 'powered',
 20: 'by',
 21: 'chestthumping',
 22: 'machismo',
 23: 'good',
 24: 'clean',
 25: 'fun',
 26: 'it',
 27: 'difficult',
 28: 'to',
 29: 'imagine',
 30: 'material',
 31: 'more',
 32: 'wrong',
 33: 'for',
 34: 'spade',
 35: 'than',
 36: 'lost',
 37: 'found',
 38: 'despite',
 39: 'gusto',
 40: 'star',
 41: 'brings',
 42: 'role',
 43: 'hard',
 44: 'ride',
 45: 'shotgun',
 46: 'on',
 47: 'hectors',
 48: 'voyage',
 49: 'discovery',
 50: 'if',
 51: 'there',
 52: 'idea',
 53: 'at',
 54: 'core',
 55: 'this',
 56: 'film',
 57: 'buried',
 58: 'in',
 59: 'unsightly',
 60: 'pile',
 61: 'flatulence',
 62: 'jokes',
 63: 'bad',
 64: 'puns',
 65: 'ridiculous',
 66: 'serial',
 67: 'plot',
 68: 'gleeson',
 69: 'goes',
 70: 'hallmark'

In [18]:
index_to_word

{'doesnt': 0,
 'answer': 1,
 'any': 2,
 'questions': 3,
 'yet': 4,
 'makes': 5,
 'its': 6,
 'point': 7,
 'like': 8,
 'rest': 9,
 'of': 10,
 'our': 11,
 'planet': 12,
 'picturesque': 13,
 'far': 14,
 'from': 15,
 'kingdom': 16,
 'wilfully': 17,
 'offensive': 18,
 'powered': 19,
 'by': 20,
 'chestthumping': 21,
 'machismo': 22,
 'good': 23,
 'clean': 24,
 'fun': 25,
 'it': 26,
 'difficult': 27,
 'to': 28,
 'imagine': 29,
 'material': 30,
 'more': 31,
 'wrong': 32,
 'for': 33,
 'spade': 34,
 'than': 35,
 'lost': 36,
 'found': 37,
 'despite': 38,
 'gusto': 39,
 'star': 40,
 'brings': 41,
 'role': 42,
 'hard': 43,
 'ride': 44,
 'shotgun': 45,
 'on': 46,
 'hectors': 47,
 'voyage': 48,
 'discovery': 49,
 'if': 50,
 'there': 51,
 'idea': 52,
 'at': 53,
 'core': 54,
 'this': 55,
 'film': 56,
 'buried': 57,
 'in': 58,
 'unsightly': 59,
 'pile': 60,
 'flatulence': 61,
 'jokes': 62,
 'bad': 63,
 'puns': 64,
 'ridiculous': 65,
 'serial': 66,
 'plot': 67,
 'gleeson': 68,
 'goes': 69,
 'hallmark': 70

In [19]:
#probability of occurrence of each word
prob_of_occurrence={}
for i in words:
    prob_of_occurrence[i]=count_of_word[i]/len(train_data["Freshness"])

In [20]:
prob_of_occurrence

{'doesnt': 0.029305555555555557,
 'answer': 0.0013819444444444445,
 'any': 0.025451388888888888,
 'questions': 0.003232638888888889,
 'yet': 0.01600347222222222,
 'makes': 0.02439236111111111,
 'its': 0.26986458333333335,
 'point': 0.00960763888888889,
 'like': 0.0732326388888889,
 'rest': 0.0036006944444444446,
 'of': 0.6430034722222222,
 'our': 0.011840277777777778,
 'planet': 0.0012847222222222223,
 'picturesque': 0.00018402777777777778,
 'far': 0.014479166666666666,
 'from': 0.07544444444444444,
 'kingdom': 0.0007673611111111111,
 'wilfully': 7.638888888888889e-05,
 'offensive': 0.0013125,
 'powered': 0.00023958333333333332,
 'by': 0.07953125,
 'chestthumping': 2.777777777777778e-05,
 'machismo': 0.00019444444444444443,
 'good': 0.038322916666666665,
 'clean': 0.0006493055555555555,
 'fun': 0.02153125,
 'it': 0.2609166666666667,
 'difficult': 0.0035833333333333333,
 'to': 0.47214930555555557,
 'imagine': 0.002673611111111111,
 'material': 0.008986111111111111,
 'more': 0.0792673611

In [21]:
#conditional probability
word_count_positive= np.zeros(len(words))
word_count_negative= np.zeros(len(words))
for i,j in zip(train_data["Freshness"],train_data["Review"]):
    for word in j.split():
#         print(word)
        if word in index_to_word:
            index=index_to_word[word]
            if(i=="fresh"):
                word_count_positive[index]+=1
            else:
                word_count_negative[index]+=1

In [22]:
word_count_positive

array([3.119e+03, 1.790e+02, 2.784e+03, ..., 2.000e+00, 5.000e+00,
       2.000e+00])

In [23]:
 word_count_negative

array([5.321e+03, 2.190e+02, 4.546e+03, ..., 3.000e+00, 1.000e+00,
       3.000e+00])

In [24]:
#conditional probobility
count_positive=0
count_negative=0
for i in train_data["Freshness"]:
    if(i=="fresh"):
        count_positive+=1
    else:
        count_negative+=1
prob_word_count_positive=word_count_positive/count_positive
prob_word_count_negative=word_count_negative/count_negative

In [25]:
prob_word_count_positive

array([2.16340318e-02, 1.24158118e-03, 1.93104022e-02, ...,
       1.38724154e-05, 3.46810385e-05, 1.38724154e-05])

In [26]:
prob_word_count_negative

array([3.69953208e-02, 1.52264147e-03, 3.16069777e-02, ...,
       2.08581023e-05, 6.95270078e-06, 2.08581023e-05])

In [27]:
alpha=1
prob_word_count_positive_smoothing=(word_count_positive+alpha)/(count_positive+alpha*len(words))
prob_word_count_negative_smoothing=(word_count_negative+alpha)/(count_negative+alpha*len(words))

In [28]:
prob_word_count_positive_smoothing

array([1.72983522e-02, 9.97981859e-04, 1.54409971e-02, ...,
       1.66330310e-05, 3.32660620e-05, 1.66330310e-05])

In [29]:
prob_word_count_negative_smoothing

array([2.95630534e-02, 1.22207286e-03, 2.52580240e-02, ...,
       2.22195065e-05, 1.11097533e-05, 2.22195065e-05])

In [30]:
prob_positive = count_positive/len(train_data)
prob_positive

0.50059375

In [31]:
prob_negative = count_negative/len(train_data)
prob_negative

0.49940625

In [32]:
for i in range(10):
    word = words[i]
    print("\n"+word+':')
    print("\tP(word|fresh):", prob_word_count_positive_smoothing[i])
    print("\tP(word|rotten):", prob_word_count_negative_smoothing[i])


doesnt:
	P(word|fresh): 0.01729835222106407
	P(word|rotten): 0.029563053404583883

answer:
	P(word|fresh): 0.0009979818589075425
	P(word|rotten): 0.001222072857761829

any:
	P(word|fresh): 0.015440997094763922
	P(word|rotten): 0.02525802401928653

questions:
	P(word|fresh): 0.003265618416091903
	P(word|rotten): 0.0019108775594094056

yet:
	P(word|fresh): 0.014698055044243862
	P(word|rotten): 0.01088755818733266

makes:
	P(word|fresh): 0.023097735690049012
	P(word|rotten): 0.015892502027529967

its:
	P(word|fresh): 0.22021578585527046
	P(word|rotten): 0.2111075313017298

point:
	P(word|fresh): 0.005378013350779535
	P(word|rotten): 0.009993223050516049

like:
	P(word|fresh): 0.04798075003881041
	P(word|rotten): 0.06909711035317906

rest:
	P(word|fresh): 0.002045862810760462
	P(word|rotten): 0.003721767339547389


In [33]:
# Development Data
def classifying(data,smoothing=True):
        v=[]
        for i in data["Review"]:
            msg1=" "
            message = i.lower()
        
            if smoothing:
                new_prob_fresh = prob_positive*len(word_count_positive)
                new_prob_rotten = prob_negative*len(word_count_negative)
            else:
                new_prob_fresh = prob_positive
                new_prob_rotten = prob_negative
            for i in message.split():
#             print(i)
                if i in index_to_word.keys():
#                 print(i)
                    index = index_to_word[i]
#                 print(index)
                    if smoothing:
                        new_prob_fresh*=prob_word_count_positive[index]+1/count_positive
                        new_prob_rotten*=prob_word_count_negative[index]+1/count_negative
                    else:
                        new_prob_fresh*=prob_word_count_positive[index]
                        new_prob_rotten*=prob_word_count_negative[index]
            if new_prob_fresh>new_prob_rotten:
                v.append("fresh")
            else:
                v.append("rotten")
         
        return v

In [34]:
a=classifying(dev_data)

In [35]:
dev_data["smoothing_prediction"] = a

C:\Users\DELL\AppData\Local\Temp\ipykernel_13624\3154281146.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dev_data["smoothing_prediction"] = a


In [36]:
dev_data

Freshness                                             Review  \
288000    rotten  tepid attempt at making alien abduction yarn i...   
288001     fresh  perfectly serviceable raceagainsttheclock thri...   
288002     fresh                    poetic pulp movie made with joy   
288003     fresh  thirst just best horror movie of year so far p...   
288004     fresh  expect same easy chemistry between two main le...   
...          ...                                                ...   
383996    rotten  if there ever film that showcases hypocrisy of...   
383997    rotten  listless troublingly familiar thriller last th...   
383998    rotten  so i didnt think movie any good no shock there...   
383999    rotten  those hoping for unintended laugh riot disappo...   
384000    rotten  film that abuses its ridiculous premise never ...   

       smoothing_prediction  
288000               rotten  
288001                fresh  
288002                fresh  
288003                fresh  
288004                fresh  
...                     ...  
383996                fresh  
383997               rotten  
383998               rotten  
383999               rotten  
384000                fresh  

[96001 rows x 3 columns]

In [37]:
dev_accuracy= sum(dev_data["smoothing_prediction"] == dev_data["Freshness"]) / len(dev_data)
print("accuarcy" ,dev_accuracy)

accuarcy 0.7959500421870606


In [38]:
a=classifying(dev_data,False)

In [39]:
dev_data["non_smoothing_prediction"] = a

C:\Users\DELL\AppData\Local\Temp\ipykernel_13624\2643654517.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dev_data["non_smoothing_prediction"] = a


In [40]:
dev_data

Freshness                                             Review  \
288000    rotten  tepid attempt at making alien abduction yarn i...   
288001     fresh  perfectly serviceable raceagainsttheclock thri...   
288002     fresh                    poetic pulp movie made with joy   
288003     fresh  thirst just best horror movie of year so far p...   
288004     fresh  expect same easy chemistry between two main le...   
...          ...                                                ...   
383996    rotten  if there ever film that showcases hypocrisy of...   
383997    rotten  listless troublingly familiar thriller last th...   
383998    rotten  so i didnt think movie any good no shock there...   
383999    rotten  those hoping for unintended laugh riot disappo...   
384000    rotten  film that abuses its ridiculous premise never ...   

       smoothing_prediction non_smoothing_prediction  
288000               rotten                   rotten  
288001                fresh                    fresh  
288002                fresh                    fresh  
288003                fresh                    fresh  
288004                fresh                    fresh  
...                     ...                      ...  
383996                fresh                    fresh  
383997               rotten                   rotten  
383998               rotten                   rotten  
383999               rotten                   rotten  
384000                fresh                    fresh  

[96001 rows x 4 columns]

In [41]:
dev_accuracy= sum(dev_data["non_smoothing_prediction"] == dev_data["Freshness"]) / len(dev_data)
print("accuarcy" ,dev_accuracy)

accuarcy 0.7947729711148842


In [42]:
positive_probs=prob_word_count_positive_smoothing/prob_word_count_negative_smoothing
negative_probs=prob_word_count_negative_smoothing/prob_word_count_positive_smoothing
fresh_top10=[]
rotten_top10=[]
for i in np.argsort(positive_probs):
    fresh_top10.append(words[i])
fresh_top10=fresh_top10[-10:]
for i in np.argsort(negative_probs):
    rotten_top10.append(words[i])
rotten_top10=rotten_top10[-10:]

In [43]:
for i in fresh_top10:
    if i in index_to_word:
        index=index_to_word[i]
        a=prob_word_count_positive_smoothing[index]
        b=prob_word_count_negative_smoothing[index]
        print(i)
        print("probability[class|word]:{} ".format(a/(a+b)))

reinvents
probability[class|word]:0.9654539952269497 
cannily
probability[class|word]:0.9654539952269497 
captivates
probability[class|word]:0.9666054558024604 
koreedas
probability[class|word]:0.9666054558024604 
tonic
probability[class|word]:0.9666054558024604 
unadorned
probability[class|word]:0.9676826331511923 
ida
probability[class|word]:0.9713758460411432 
nimbly
probability[class|word]:0.9729230181668167 
unmissable
probability[class|word]:0.9736355346988487 
spiderverse
probability[class|word]:0.9755645525334212 


In [44]:
for i in rotten_top10:
    if i in index_to_word:
        index=index_to_word[i]
        a=prob_word_count_positive_smoothing[index]
        b=prob_word_count_negative_smoothing[index]
        print(i)
        print("probability[class|word]:{} ".format(b/(a+b)))

drearily
probability[class|word]:0.9706423676059199 
unfunny
probability[class|word]:0.9712346288653219 
thirdrate
probability[class|word]:0.9714812025477481 
lifeless
probability[class|word]:0.9719268325232326 
feeble
probability[class|word]:0.9741857038970713 
unexciting
probability[class|word]:0.975046221225918 
flavorless
probability[class|word]:0.9778189801477026 
squanders
probability[class|word]:0.9784184917496185 
mirthless
probability[class|word]:0.9824888238849712 
charmless
probability[class|word]:0.9930201603538501 


In [45]:
a=classifying(test_data)

In [46]:
test_data["prediction"]=a

C:\Users\DELL\AppData\Local\Temp\ipykernel_13624\2370575236.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_data["prediction"]=a


In [47]:
test_accuracy= sum(test_data["prediction"] == test_data["Freshness"]) / len(test_data)
print("accuarcy" ,dev_accuracy)

accuarcy 0.7947729711148842
